### ISSUE TITLE
Starter Code for C++ 

### ISSUE THREAD

**Issue by TilakChad** [Bhoos/smartbots-2023-starter-code#15]
There doesn't seem to be a starter code for C++. 

Would be okay to open a PR submitting code for C++?

**Comment by pSapien** [comment]
@TilakChad Yeah sure. 

Please make sure 

1. The documentation is written and clear on how to start the bot.
2. The bot plays a valid move. You could test it out against the sandbox while playing 5-6 games. If there are no errors, that means the code works well.

We'll be waiting for your PR.

**Comment by pSapien** [comment]
closed by https://github.com/Bhoos/smartbots-2023-starter-code/pull/16
